(part "RBS040200"
    (packageRef "RBS040200")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "Assemtech")
    (property "Manufacturer_Part_Number" "RBS040200")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "15 , 25 mA, 24V, Non-Mercury Tilt Switch")
    (property "Datasheet_Link" "http://uk.rs-online.com/web/p/products/3615093")
    (property "symbolName1" "RBS040200")
)
